### ISSUE TITLE
LCMPT does not labels for broader and narrower

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#184]
authority: LCMPT
search query: band
loc id: mp2013015048
loc rwo uri: <http://id.loc.gov/authorities/performanceMediums/mp2013015048>

id.loc.gov has these triples related to broader and narrower...

```
<http://id.loc.gov/authorities/performanceMediums/mp2013015048> <skos:broader> <http://id.loc.gov/authorities/performanceMediums/mp2013015812> .
<http://id.loc.gov/authorities/performanceMediums/mp2013015812> <skos:prefLabel> "instrumental ensemble"@en . 
<http://id.loc.gov/authorities/performanceMediums/mp2013015048> <skos:narrower> <http://id.loc.gov/authorities/performanceMediums/mp2013015262> .
<http://id.loc.gov/authorities/performanceMediums/mp2013015262> <skos:prefLabel> 
"fife and drum corps" @en .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_performance_batch.jsp?query=band&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to broader and narrower...

```
<http://id.loc.gov/authorities/performanceMediums/mp2013015048> <madsrdf:broader> <http://id.loc.gov/authorities/performanceMediums/mp2013015812> .<http://id.loc.gov/authorities/performanceMediums/mp2013015048> <madsrdf:narrower> <http://id.loc.gov/authorities/performanceMediums/mp2013015262> .
```

Missing triple...

```
<http://id.loc.gov/authorities/performanceMediums/mp2013015812> <skos:prefLabel> "instrumental ensemble"@en . 
<http://id.loc.gov/authorities/performanceMediums/mp2013015262> <skos:prefLabel> 
"fife and drum corps" @en .
```

### Related Issues

#183 LCMPT does not include Citation note, source, or status in search results
#13 Request authority LCMPT be supported

**Comment by eichmann** [comment]
@elrayle fix deployed and ready for validation.

**Comment by elrayle** [comment]
Verified that broader and narrower labels are present, but id is still missing.  This is similar to LCDGT broader and narrower issue #191.  See comment https://github.com/LD4P/qa_server/issues/191#issuecomment-531332606

**Comment by eichmann** [comment]
@elrayle ids now present for broader/narrower URIs.

**Comment by elrayle** [comment]
Closing: Verified using http://localhost:3000/authorities/search/linked_data/locperformance_ld4l_cache?q=band&maxRecords=20&context=true
