### ISSUE TITLE
LCSH does not labels for broader and narrower

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#186]
authority: LCSH
search query: Cognitive science
loc id: sh88006179
loc rwo uri: <http://id.loc.gov/authorities/subjects/sh88006179>

id.loc.gov has these triples related to broader and narrower...

```
<http://id.loc.gov/authorities/subjects/sh88006179> <skos:broader> <http://id.loc.gov/authorities/subjects/sh00007934> .
<http://id.loc.gov/authorities/subjects/sh00007934> <skos:prefLabel> "Science @en . 
<http://id.loc.gov/authorities/subjects/sh88006179> <skos:narrower> <http://id.loc.gov/authorities/subjects/sh91002431> .
<http://id.loc.gov/authorities/subjects/sh91002431> <skos:prefLabel> 
"Philosophy and cognitive science" @en .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_subject_batch.jsp?query=Cognitive%20science&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to broader and narrower...

```
<http://id.loc.gov/authorities/subjects/sh88006179> <skos:broader> <http://id.loc.gov/authorities/subjects/sh00007934> .
<http://id.loc.gov/authorities/subjects/sh88006179> <skos:narrower> <http://id.loc.gov/authorities/subjects/sh91002431> .
```

Missing triple...

```
<http://id.loc.gov/authorities/subjects/sh00007934> <skos:prefLabel> "Science @en . 
<http://id.loc.gov/authorities/subjects/sh91002431> <skos:prefLabel> 
"Philosophy and cognitive science" @en .
```

### Related Issues

#185 LCSH does not include Citation note, source, or status in search results
#116 Implement LDPath for LCSH in DAVE and QA

**Comment by eichmann** [comment]
@elrayle fix deployed and ready for validation. Note there seems to be a separate issue with this where we're over generating results, I think because the first search result is also the exact match.  Please submit a separate issue if this is true.

**Comment by elrayle** [comment]
Verified that broader and narrower labels are present, but id is still missing. This is similar to LCDGT broader and narrower issue #191. See comment #191 (comment)

**Comment by eichmann** [comment]
@elrayle ids now present for broader/narrower URIs

**Comment by elrayle** [comment]
Closing: Verified using http://localhost:3000/authorities/search/linked_data/locsubjects_ld4l_cache?q=Cognitive%20science&maxRecords=5&context=true
