### ISSUE TITLE
LCDGT does not labels or ids for broader and narrower

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#191]
authority: LCDGT
search query: Dancers
loc id: dg2015060747
loc rwo uri: <http://id.loc.gov/authorities/demographicTerms/dg2015060747>

id.loc.gov has these triples related to broader and narrower...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060747> <skos:broader> <http://id.loc.gov/authorities/demographicTerms/dg2015060132 > .
<http://id.loc.gov/authorities/demographicTerms/dg2015060132 > <skos:prefLabel> "Artists"@en . 
<http://id.loc.gov/authorities/demographicTerms/dg2015060747> <skos:narrower> <http://id.loc.gov/authorities/demographicTerms/dg2015060748 > .
<http://id.loc.gov/authorities/demographicTerms/dg2015060748 > <skos:prefLabel> 
"Ballet dancers" @en .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_demographics_batch.jsp?query=dancers&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to broader and narrower...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060747> <madsrdf:broader> <http://id.loc.gov/authorities/demographicTerms/dg2015060132> .<http://id.loc.gov/authorities/demographicTerms/dg2015060747> <madsrdf:narrower> <http://id.loc.gov/authorities/demographicTerms/dg2015060748> .
```

Missing triple...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060132 > <skos:prefLabel> "Artists"@en . 
<http://id.loc.gov/authorities/demographicTerms/dg2015060748 > <skos:prefLabel> 
"Ballet dancers" @en .
```

### Related Issues

#192 LCDGT does not include Citation note, source, or status in search results
#194 LCDGT does not include Variant in search results
#195 LCDGT does not include Related in search results
#196 LCDGT does not include Earlier Established Form in search results
#26 Request authority LCDGT (Library of Congress Demographic Group Terms) be supported

**Comment by eichmann** [comment]
@elrayle fix deployed and ready for validation.

**Comment by elrayle** [comment]
@eichmann I confirmed that broader and narrower labels are now in search results.  The ID still doesn't show up.  They are defined to come in with triple...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060748> <loc:lccn> "dg2015060748" .
```

The id is present for LCGFT.  I looked at cache results for that auth and it looks like you are bringing in the entire broader term into the search results graph.

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_genre_batch.jsp?query=animation&maxRecords=1&startRecord=1&lang=en&context=true'

returns related triples...

```
<http://id.loc.gov/authorities/genreForms/gf2011026181> <http://www.w3.org/2004/02/skos/core#broader> <http://id.loc.gov/authorities/genreForms/gf2011026049> .
```

plus all triples for `<http://id.loc.gov/authorities/genreForms/gf2011026049>` even though it is not a search result.

This same approach could work here.

**Comment by eichmann** [comment]
@eichmann prefLabel and lccn both now appear for broader and narrower.  Ready for validation

**Comment by elrayle** [comment]
Closing: Verified using http://localhost:3000/authorities/search/linked_data/locdemographics_ld4l_cache?q=Biologists&maxRecords=5&context=true
